volumes:
  postgres:
services:
  database:
    image: postgres:13
    container_name: rps-db
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./data:/tmp/dump
    environment:
      POSTGRES_PASSWORD: ${DB_PASS:-rps}
      POSTGRES_USER: ${DB_USER:-rps}
      POSTGRES_DB: ${DB_NAME:-rps}
  cache:
    image: redis:latest
    container_name: rps-cache
    ports:
      - 127.0.0.1:6379:6379
