[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "uv run uvicorn app:create_app --factory --host 0.0.0.0 --port 8000"
preDeployCommand = ["uv run alembic upgrade head"]
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10