"""init

Revision ID: 42246a04aa69
Revises: 
Create Date: 2025-03-19 11:59:41.129984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42246a04aa69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('last_login_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('match_join',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('player_id', sa.String(length=200), nullable=False),
    sa.Column('match_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_result',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('winner_move', sa.String(length=10), nullable=True),
    sa.Column('loser_move', sa.String(length=10), nullable=True),
    sa.Column('winner_id', sa.String(length=200), nullable=False),
    sa.Column('loser_id', sa.String(length=200), nullable=False),
    sa.Column('match_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['loser_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_result')
    op.drop_table('match_join')
    op.drop_table('player')
    op.drop_table('match')
    # ### end Alembic commands ###